### ISSUE TITLE
error downloading due to consent to use advertising data pop up.

### ISSUE THREAD

**Issue by zukigay** [Intenzi/ShowdownReplayDownloader#4]
here is the output video and log.

[replay-lm8kylqhb5o8mb.webm](https://github.com/Intenzi/ShowdownReplayDownloader/assets/55743069/7c096eaf-38ee-4100-a02c-4ff5ba06d4fc)
```
--Booting Downloader--
Opened replay undefined vs undefined ([Gen 9] NatDex Draft)
Saving Replay..  (this may take a while.. preferably not more than 2.10 minutes)
[*estimates are calced at normal speed*]
Finished recording https://replay.pokemonshowdown.com/gen9natdexdraft-2067600362
Recording Saved!
Location -> replays/replay-lm8kylqhb5o8mb.webm
Thankyou for utilising Showdown Replay Downloader!!
/home/zuki/src/ShowdownReplayDownloader/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:138
            this._reject(callback, new Errors_js_1.TargetCloseError('Target closed'));
                                   ^

TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
    at CallbackRegistry.clear (/home/zuki/src/ShowdownReplayDownload
er/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:138:36)
    at CDPSessionImpl._onClosed (/home/zuki/src/ShowdownReplayDownloader/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:451:25)
    at Connection.onMessage (/home/zuki/src/ShowdownReplayDownloader/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:248:25)
    at WebSocket.<anonymous> (/home/zuki/src/ShowdownReplayDownloader/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NodeWebSocketTransport.js:52:32)
    at callListener (/home/zuki/src/ShowdownReplayDownloader/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/zuki/src/ShowdownReplayDownloader/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/home/zuki/src/ShowdownReplayDownloader/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/home/zuki/src/ShowdownReplayDownloader/node_modules/puppeteer-core/node_modules/ws/lib/receiver.js:541:14)

Node.js v21.6.2
```

**Comment by zukigay** [comment]
forgot to include but the command i ran was 
```
node download.js -l https://replay.pokemonshowdown.com/gen9natdexdraft-2067600362
```

**Comment by Intenzi** [comment]
Thankyou for the report! I am trying to replicate the issue on my end. 
This might be a region-based consent popup as I have been unable to have it show up.
The source code for client doesn't seem to contain it either, I'll ask on discord for some clarification of it!
